bridge.version=0.3.0-poc.2
bridge.release=6
bridge.protocol=2
minecraft.version=26.2
paper.build=126
valhalla.version=1.10.3
gun-core.version=1.0.15
modern-guns.version=1.9.3
valhalla.marker=1010003
gun-core.marker=1000015
modern-guns.marker=1009003
